services:
  node-api:
    build: ./backend-node
    command: node server.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres

  node-worker:
    build: ./backend-node
    command: node worker.js
    depends_on:
      - redis
      - go-service

  go-service:
    build: ./backend-go
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: querypulse

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
